# $OpenBSD: Makefile,v 1.3 2010/11/22 08:36:48 espie Exp $

COMMENT =	3 column, tableless layout theme with wide image banner
DISTNAME=	marinelli-6.x-2.96
PKGNAME =	drupal6-theme-marinelli-2.96
REVISION =	0

MODDRUPAL_THEME =	Yes

.include <bsd.port.mk>
