# $OpenBSD: Makefile,v 1.11 2012/01/28 11:20:52 espie Exp $

COMMENT =	date cck and api for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

V =		2.9
DISTNAME = 	date-6.x-$V
PKGNAME =	drupal6-date-$V

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
