# $OpenBSD: Makefile,v 1.4 2010/11/15 09:05:41 stephan Exp $

COMMENT =	automatically update translations

DISTNAME = 	l10n_update-6.x-1.0-beta3
PKGNAME =	drupal6-l10n_update-1.0-beta3

.include <bsd.port.mk>
