# $OpenBSD: Makefile,v 1.4 2010/11/15 09:05:41 stephan Exp $

COMMENT =	calendar view for date fields

DISTNAME = 	calendar-6.x-2.4
PKGNAME =	drupal6-calendar-2.4
REVISION =	0

.include <bsd.port.mk>
