# $OpenBSD: Makefile,v 1.4 2010/11/15 09:05:41 stephan Exp $

COMMENT =	makes inserting images and links to files easier
DISTNAME = 	insert-6.x-1.1
PKGNAME =	drupal6-insert-1.7
#REVISION =	0

.include <bsd.port.mk>
