# $OpenBSD: Makefile,v 1.4 2010/11/15 09:05:41 stephan Exp $

COMMENT =	help users uploading images

DISTNAME = 	img_assist-6.x-2.0-alpha4
PKGNAME =	drupal6-image_assist-2.0
REVISION =	0

.include <bsd.port.mk>
