# $OpenBSD: Makefile,v 1.4 2010/11/15 09:05:41 stephan Exp $

COMMENT =	per forum access control and moderator roles
V =		1.8
DISTNAME = 	forum_access-6.x-${V}
PKGNAME =	drupal6-forum-access-${V}

RUN_DEPENDS =   www/drupal6/acl

.include <bsd.port.mk>
